### ISSUE TITLE
Add GPS tracking to Kliva

### ISSUE THREAD

**Issue by Depechie** [AppCreativity/Kliva#64]
Be able to track a route with Kliva and upload result to Strava

Look at https://channel9.msdn.com/Events/Build/2015/3-626 for details on Extended Execution ( ExtendedExecutionSession ) to keep the app active for a long time ( during tracking )
- [ ] Be sure to verify GPS hardware to only show route tracking for those devices that have one
- [ ] Auto pause of tracking when speed is underneath certain value? ( config option? )
- [x] GPX writer to store geo locations on disk

**Comment by Depechie** [comment]
- [x] Design GPS tracking screen
- [x] Get current location of device
- [x] Request extended execution for Location Tracking
- [x] Implement periodic timer to request current location 
- [x] Upload tracked ride to Strava

**Comment by Depechie** [comment]
- [x] Show current tracking on screen as route ( currently only current position dot is shown )
- [ ] Show current speed

possible design : https://www.pinterest.com/pin/423619908678573458/

**Comment by PieEatingNinjas** [comment]
- [ ] make an alternative 'Battery Saver mode' (black screen with only speed and time and stop/pause buttons).

**Comment by bartlannoeye** [comment]
I'd also increase the interval in battery saver mode to take a few less coordinates (eg. once per 5-10s)

**Comment by Depechie** [comment]
![tracking](https://cloud.githubusercontent.com/assets/351693/19959794/53b2137c-a1a9-11e6-8c65-738c45a7ccb0.png)
Nice design bottom right small overview current time with pause button
